(ns formation.facts
  "Per-jurisdiction incorporation requirement catalog -- the G2-style
  spec-basis table the RegistrarGovernor checks every jurisdiction/assess
  proposal against ('did the advisor cite an OFFICIAL public source for
  this jurisdiction's requirements, or did it invent one?').

  Coverage is reported HONESTLY (see `coverage`), the same discipline
  `matsurigoto` (etzhayyim/root, ADR-2606062300) uses for its country
  profiles and `ooyake` (etzhayyim/root) uses for its civic wayfinding
  seed: a jurisdiction not in this table has NO spec-basis, full stop --
  the advisor must not fabricate one, and the governor holds if it tries.

  Seed values are drawn from each jurisdiction's official companies
  registry (see `:provenance`); they are a STARTING catalog, not a
  from-scratch survey of all ~194 jurisdictions. Extending coverage is
  additive: add one map to `catalog`, cite a real source, done -- never
  invent a jurisdiction's requirements to make coverage look bigger.")

(def catalog
  "iso3 -> requirement map. `:required-docs` mirrors the generic filing
  checklist every registry asks for in some form; `:legal-basis` /
  `:owner-authority` / `:provenance` are the G2 citation the governor
  requires before any :jurisdiction/assess proposal can commit."
  {"JPN" {:name "Japan"
          :owner-authority "法務局 (Legal Affairs Bureau)"
          :legal-basis "商業登記法 / 会社法"
          :national-spec "登記・供託オンライン申請システム"
          :provenance "https://www.moj.go.jp/MINJI/minji06.html"
          :required-docs ["定款 (articles of incorporation, notarised for 株式会社)"
                          "発起人・取締役の本人確認書類"
                          "本店所在地の証明"
                          "資本金の払込証明"
                          "登記申請書 + 登録免許税"]}
   "USA-DE" {:name "United States -- Delaware (exemplar; federalism note below)"
             :owner-authority "Delaware Division of Corporations"
             :legal-basis "Delaware General Corporation Law (Title 8)"
             :national-spec "Delaware One Stop / DCIS"
             :provenance "https://corp.delaware.gov/"
             :notes "No federal corporate registry -- incorporation is per-state; Delaware is an exemplar, not a national authority."
             :required-docs ["Certificate of Incorporation"
                             "Registered agent with a Delaware address"
                             "Incorporator identification"
                             "Franchise tax / filing fee"]}
   "GBR" {:name "United Kingdom"
          :owner-authority "Companies House"
          :legal-basis "Companies Act 2006"
          :national-spec "Companies House online + API / GLEIF LEI"
          :provenance "https://www.gov.uk/government/organisations/companies-house"
          :required-docs ["Proposed company name (availability check)"
                          "Registered office address"
                          "Director + PSC (person of significant control) identification"
                          "Memorandum + Articles of Association"
                          "Filing fee"]}
   "DEU" {:name "Germany"
          :owner-authority "Amtsgericht -- Handelsregister"
          :legal-basis "Handelsgesetzbuch (HGB)"
          :national-spec "Handelsregister / unternehmensregister.de + EU BRIS"
          :provenance "https://www.handelsregister.de/"
          :required-docs ["Notarised Gesellschaftsvertrag (articles)"
                          "Managing director identification"
                          "Registered office address"
                          "Minimum share capital deposit proof (GmbH: EUR 25,000 / 12,500 paid-in)"]}
   "EST" {:name "Estonia"
          :owner-authority "Centre of Registers and Information Systems (RIK)"
          :legal-basis "Commercial Code (Äriseadustik)"
          :national-spec "e-Business Register (company in minutes)"
          :provenance "https://www.rik.ee/en"
          :required-docs ["e-Residency or Estonian ID/eID"
                          "Articles of association"
                          "Registered office / contact person (for non-resident founders)"
                          "Share capital declaration"]}
   "KOR" {:name "South Korea"
          :owner-authority "대법원 등기소 (Court Registry)"
          :legal-basis "상법 / 상업등기법"
          :national-spec "인터넷등기소 (IROS)"
          :provenance "https://www.iros.go.kr/"
          :required-docs ["정관 (articles of incorporation)"
                          "발기인·이사 신원 확인"
                          "본점 소재지 증명"
                          "자본금 납입 증명"]}
   "IND" {:name "India"
          :owner-authority "Ministry of Corporate Affairs (MCA)"
          :legal-basis "Companies Act 2013"
          :national-spec "MCA21 / SPICe+"
          :provenance "https://www.mca.gov.in/"
          :required-docs ["Digital Signature Certificate (DSC) for each director"
                          "Director Identification Number (DIN)"
                          "Memorandum + Articles of Association"
                          "Registered office proof"]}
   "SGP" {:name "Singapore"
          :owner-authority "Accounting and Corporate Regulatory Authority (ACRA)"
          :legal-basis "Companies Act 1967"
          :national-spec "BizFile+"
          :provenance "https://www.acra.gov.sg/"
          :required-docs ["Proposed name (ACRA name-availability check)"
                          "Registered office address in Singapore"
                          "At least one locally resident director"
                          "Company constitution"]}
   "NZL" {:name "New Zealand"
          :owner-authority "New Zealand Companies Office"
          :legal-basis "Companies Act 1993"
          :national-spec "Companies Register (companiesoffice.govt.nz)"
          :provenance "https://companies-register.companiesoffice.govt.nz/"
          :required-docs ["Reserved company name"
                          "At least one director who lives in NZ or Australia"
                          "Registered office + address for service"
                          "Consent forms for directors + shareholders"]}
   "CAN" {:name "Canada"
          :owner-authority "Corporations Canada (federal) / provincial registries"
          :legal-basis "Canada Business Corporations Act"
          :national-spec "Corporations Canada online filing"
          :provenance "https://ised-isde.canada.ca/site/corporations-canada/en"
          :notes "Federal incorporation coexists with 13 provincial/territorial registries; this entry covers the federal path only."
          :required-docs ["NUANS name search report"
                          "Articles of Incorporation"
                          "Registered office address in Canada"
                          "Initial director(s) identification"]}
   "FRA" {:name "France"
          :owner-authority "Institut National de la Statistique et des Études Économiques (INSEE) / Guichet unique (INPI)"
          :legal-basis "Code de commerce"
          :national-spec "Guichet unique des formalités d'entreprises (formalites.entreprises.gouv.fr)"
          :provenance "https://www.insee.fr/fr/information/2028129"
          :required-docs ["Statuts (articles of association)"
                          "Justificatif de domiciliation (registered office proof)"
                          "Identification des dirigeants et bénéficiaires effectifs"
                          "Dépôt du capital social (proof of paid-in capital)"
                          "Déclaration de non-condamnation et filiation"]}
   "NOR" {:name "Norway"
          :owner-authority "Brønnøysundregistrene (Brønnøysund Register Centre)"
          :legal-basis "Aksjeloven (Limited Liability Companies Act)"
          :national-spec "Samordnet registermelding via Altinn"
          :provenance "https://www.brreg.no/"
          :required-docs ["Stiftelsesdokument (founding document) + vedtekter (articles)"
                          "Identification of founders/board members"
                          "Registered business address in Norway"
                          "Proof of minimum share capital (NOK 30,000)"]}
   "DNK" {:name "Denmark"
          :owner-authority "Erhvervsstyrelsen (Danish Business Authority) -- CVR register"
          :legal-basis "Selskabsloven (Danish Companies Act)"
          :national-spec "Virk.dk digital registration"
          :provenance "https://datacvr.virk.dk/"
          :required-docs ["Stiftelsesdokument (memorandum of association)"
                          "Vedtægter (articles of association)"
                          "Director/owner identification (MitID or equivalent)"
                          "Proof of minimum capital (ApS: DKK 40,000)"]}
   "FIN" {:name "Finland"
          :owner-authority "Patentti- ja rekisterihallitus (PRH, Finnish Patent and Registration Office)"
          :legal-basis "Osakeyhtiölaki (Limited Liability Companies Act)"
          :national-spec "YTJ / Business Information System online notification"
          :provenance "https://www.prh.fi/en/kaupparekisteri.html"
          :required-docs ["Perustamissopimus (memorandum of association)"
                          "Yhtiöjärjestys (articles of association)"
                          "Founder/board identification"
                          "Proof of minimum share capital (Oy: EUR 2,500)"]}
   "BEL" {:name "Belgium"
          :owner-authority "Kruispuntbank van Ondernemingen / Banque-Carrefour des Entreprises (KBO/BCE)"
          :legal-basis "Code des sociétés et des associations (CSA/WVV)"
          :national-spec "e-Guichet / notarial deed filing via KBO/BCE"
          :provenance "https://kbopub.economie.fgov.be/"
          :required-docs ["Notarised articles of association (for most company forms)"
                          "Registered office address in Belgium"
                          "Director/founder identification"
                          "Financial plan (plan financier)"]}
   "CZE" {:name "Czech Republic"
          :owner-authority "Administrativní registr ekonomických subjektů (ARES)"
          :legal-basis "Zákon o obchodních korporacích (Business Corporations Act)"
          :national-spec "ARES / obchodní rejstřík (Commercial Register) online filing"
          :provenance "https://ares.gov.cz/"
          :required-docs ["Zakladatelská listina / společenská smlouva (founding deed)"
                          "Registered office proof"
                          "Statutory body (jednatel) identification"
                          "Proof of minimum share capital (s.r.o.: CZK 1)"]}
   "AUS" {:name "Australia"
          :owner-authority "Australian Securities and Investments Commission (ASIC)"
          :legal-basis "Corporations Act 2001 (Cth)"
          :national-spec "ASIC online company registration"
          :provenance "https://asic.gov.au/for-business/registering-a-company/"
          :required-docs ["Proposed company name (ASIC availability check)"
                          "Registered office address in Australia"
                          "At least one director who ordinarily resides in Australia"
                          "Consent to act as director/member"]}
   "ZAF" {:name "South Africa"
          :owner-authority "Companies and Intellectual Property Commission (CIPC)"
          :legal-basis "Companies Act 71 of 2008"
          :national-spec "CIPC online company registration (BizPortal)"
          :provenance "https://www.cipc.co.za/"
          :required-docs ["Reserved company name (or standard NAP name)"
                          "Memorandum of Incorporation (MOI)"
                          "Director identification (ID/passport)"
                          "Registered office address in South Africa"]}
   "CHE" {:name "Switzerland"
          :owner-authority "Eidgenössisches Amt für das Handelsregister -- Zefix (Central Business Names Index)"
          :legal-basis "Schweizerisches Obligationenrecht (Code of Obligations)"
          :national-spec "Zefix / cantonal commercial register online filing"
          :provenance "https://www.zefix.ch/"
          :required-docs ["Notarised articles of association (Statuten)"
                          "Registered office address in Switzerland"
                          "Director/founder identification"
                          "Proof of minimum share capital (AG: CHF 100,000, 50,000 paid-in)"]}
   "NLD" {:name "Netherlands"
          :owner-authority "Kamer van Koophandel (KVK, Dutch Chamber of Commerce)"
          :legal-basis "Burgerlijk Wetboek Boek 2 (Dutch Civil Code, Book 2)"
          :national-spec "KVK Handelsregister online registration"
          :provenance "https://www.kvk.nl/"
          :required-docs ["Notarised deed of incorporation (oprichtingsakte)"
                          "Registered office address in the Netherlands"
                          "Director/UBO identification"
                          "Proof of share capital deposit"]}
   "ISR" {:name "Israel"
          :owner-authority "רשם החברות (Registrar of Companies), Ministry of Justice"
          :legal-basis "חוק החברות (Companies Law, 5759-1999)"
          :national-spec "Registrar of Companies online e-filing"
          :provenance "https://www.gov.il/en/departments/the_registrar_of_companies"
          :required-docs ["Articles of association (תקנון)"
                          "Founder/director identification"
                          "Registered office address in Israel"
                          "Declaration of first directors and capital"]}
   "IRL" {:name "Ireland"
          :owner-authority "Companies Registration Office (CRO)"
          :legal-basis "Companies Act 2014"
          :national-spec "CRO CORE online filing"
          :provenance "https://www.cro.ie/"
          :required-docs ["Constitution (memorandum + articles)"
                          "Director/secretary identification"
                          "Registered office address in Ireland"
                          "Form A1 incorporation filing"]}
   "HKG" {:name "Hong Kong"
          :owner-authority "Companies Registry"
          :legal-basis "Companies Ordinance (Cap. 622)"
          :national-spec "e-Registry / Companies Registry online filing"
          :provenance "https://www.cr.gov.hk/"
          :required-docs ["Articles of association"
                          "Incorporation Form (NNC1/NNC1G)"
                          "Registered office address in Hong Kong"
                          "Director/company secretary identification"]}
   "PRT" {:name "Portugal"
          :owner-authority "Instituto dos Registos e do Notariado (IRN)"
          :legal-basis "Código das Sociedades Comerciais"
          :national-spec "Empresa na Hora / Empresa Online"
          :provenance "https://www.irn.mj.pt/"
          :required-docs ["Pacto social (articles of association)"
                          "Founder/director identification"
                          "Registered office address in Portugal"
                          "Capital declaration"]}
   "ESP" {:name "Spain"
          :owner-authority "Registro Mercantil Central"
          :legal-basis "Ley de Sociedades de Capital"
          :national-spec "CIRCE / Registro Mercantil online filing"
          :provenance "https://www.rmc.es/"
          :required-docs ["Escritura pública de constitución (notarised deed)"
                          "Certificación negativa de denominación (name reservation)"
                          "Founder/director identification"
                          "Proof of paid-in capital"]}
   "ITA" {:name "Italy"
          :owner-authority "Registro delle Imprese (Chambers of Commerce)"
          :legal-basis "Codice Civile"
          :national-spec "ComUnica / Registro Imprese online filing"
          :provenance "https://www.registroimprese.it/"
          :required-docs ["Atto costitutivo e statuto (notarised deed + statute)"
                          "Founder/director identification"
                          "Registered office address in Italy"
                          "Proof of paid-in capital"]}
   "SWE" {:name "Sweden"
          :owner-authority "Bolagsverket (Swedish Companies Registration Office)"
          :legal-basis "Aktiebolagslagen (Companies Act)"
          :national-spec "Bolagsverket e-tjänst online filing"
          :provenance "https://www.bolagsverket.se/"
          :required-docs ["Stiftelseurkund (memorandum of association)"
                          "Bolagsordning (articles of association)"
                          "Founder/board identification"
                          "Proof of minimum share capital (AB: SEK 25,000)"]}
   "POL" {:name "Poland"
          :owner-authority "Krajowy Rejestr Sądowy (KRS, National Court Register)"
          :legal-basis "Kodeks spółek handlowych (Commercial Companies Code)"
          :national-spec "Portal Rejestrów Sądowych (PRS) / S24 online filing"
          :provenance "https://ekrs.ms.gov.pl/"
          :required-docs ["Umowa spółki (articles of association)"
                          "Founder/board identification"
                          "Registered office address in Poland"
                          "Proof of minimum share capital (sp. z o.o.: PLN 5,000)"]}
   "MEX" {:name "Mexico"
          :owner-authority "Secretaría de Economía -- Registro Único de Garantías Mobiliarias / Registro Público de Comercio"
          :legal-basis "Ley General de Sociedades Mercantiles"
          :national-spec "Sistema Electrónico de Publicaciones de Sociedades Mercantiles (PSM)"
          :provenance "https://www.gob.mx/se"
          :required-docs ["Acta constitutiva (notarised incorporation deed)"
                          "Founder/administrator identification"
                          "Registered office address in Mexico"
                          "RFC (tax ID) registration"]}
   "BRA" {:name "Brazil"
          :owner-authority "Receita Federal (CNPJ) / Junta Comercial (state-level commercial registry)"
          :legal-basis "Código Civil / Lei das Sociedades por Ações"
          :national-spec "Redesim / Junta Comercial online filing"
          :provenance "https://www.gov.br/receitafederal/"
          :notes "Company registration is state-level (Junta Comercial) plus federal CNPJ tax registration; this entry covers the combined federal+state filing path."
          :required-docs ["Contrato social (articles of association)"
                          "Founder/administrator identification (CPF)"
                          "Registered office address in Brazil"
                          "CNPJ (federal tax ID) registration"]}
   ;; ---- R1 expansion (2026-07-12): ten additional jurisdictions, same
   ;; discipline -- every entry cites the real national registry authority.
   "CHN" {:name "China"
          :owner-authority "国家市场监督管理总局 (State Administration for Market Regulation, SAMR) / local AMR branches"
          :legal-basis "中华人民共和国公司法 (Company Law of the PRC, 2023 revision)"
          :national-spec "国家企业信用信息公示系统 (National Enterprise Credit Information Publicity System)"
          :provenance "https://www.samr.gov.cn/"
          :required-docs ["章程 (articles of association)"
                          "Shareholder and legal-representative identification"
                          "Registered address proof"
                          "Registered capital subscription declaration"
                          "Business scope registration"]}
   "IDN" {:name "Indonesia"
          :owner-authority "Kementerian Hukum — Direktorat Jenderal Administrasi Hukum Umum (AHU)"
          :legal-basis "UU No. 40 Tahun 2007 tentang Perseroan Terbatas (as amended by the Job Creation Law)"
          :national-spec "AHU Online + OSS (Online Single Submission) risk-based licensing"
          :provenance "https://ahu.go.id/"
          :required-docs ["Notarial deed of establishment (akta pendirian)"
                          "Ministerial ratification (SK Kemenkumham)"
                          "NIB (business identification number) via OSS"
                          "Registered domicile"
                          "Founder identification / NPWP"]}
   "TUR" {:name "Türkiye"
          :owner-authority "Ticaret Bakanlığı / Trade Registry Directorates (Ticaret Sicili Müdürlükleri)"
          :legal-basis "Türk Ticaret Kanunu No. 6102"
          :national-spec "MERSIS (Merkezi Sicil Kayıt Sistemi)"
          :provenance "https://mersis.ticaret.gov.tr/"
          :required-docs ["Articles of association drafted in MERSIS"
                          "Founder identification / tax number"
                          "Registered office address"
                          "Capital deposit bank letter (for joint-stock companies)"
                          "Trade registry application"]}
   "THA" {:name "Thailand"
          :owner-authority "Department of Business Development (DBD), Ministry of Commerce"
          :legal-basis "Civil and Commercial Code (Title XXII) / Public Limited Companies Act B.E. 2535"
          :national-spec "DBD e-Registration"
          :provenance "https://www.dbd.go.th/"
          :required-docs ["Memorandum of association"
                          "Statutory meeting minutes"
                          "Promoter/director identification"
                          "Registered office address in Thailand"
                          "Share subscription list"]}
   "VNM" {:name "Vietnam"
          :owner-authority "Provincial Business Registration Offices / Agency for Business Registration (Ministry of Planning and Investment lineage)"
          :legal-basis "Luật Doanh nghiệp No. 59/2020/QH14 (Law on Enterprises 2020)"
          :national-spec "National Business Registration Portal"
          :provenance "https://dangkykinhdoanh.gov.vn/"
          :required-docs ["Enterprise registration application"
                          "Company charter"
                          "Member/shareholder list"
                          "Founder identification"
                          "Registered office address in Vietnam"]}
   "PHL" {:name "Philippines"
          :owner-authority "Securities and Exchange Commission (SEC)"
          :legal-basis "Revised Corporation Code (Republic Act No. 11232, 2019)"
          :national-spec "SEC eSPARC / OneSEC"
          :provenance "https://www.sec.gov.ph/"
          :required-docs ["Articles of incorporation"
                          "Bylaws (or one-person-corporation alternative)"
                          "Incorporator identification / TIN"
                          "Registered office address"
                          "Capital structure declaration"]}
   "MYS" {:name "Malaysia"
          :owner-authority "Suruhanjaya Syarikat Malaysia (SSM, Companies Commission of Malaysia)"
          :legal-basis "Companies Act 2016 (Act 777)"
          :national-spec "MyCoID"
          :provenance "https://www.ssm.com.my/"
          :required-docs ["Incorporation superform (Section 14)"
                          "Company name reservation"
                          "Director/promoter identification"
                          "Registered office address in Malaysia"
                          "Constitution (optional under Act 777)"]}
   "NGA" {:name "Nigeria"
          :owner-authority "Corporate Affairs Commission (CAC)"
          :legal-basis "Companies and Allied Matters Act (CAMA) 2020"
          :national-spec "CAC Company Registration Portal"
          :provenance "https://www.cac.gov.ng/"
          :required-docs ["Memorandum and articles of association"
                          "Director/shareholder identification"
                          "Registered office address in Nigeria"
                          "Statement of share capital"
                          "Company name reservation"]}
   "ARG" {:name "Argentina"
          :owner-authority "Inspección General de Justicia (IGJ, CABA) / provincial Registros Públicos"
          :legal-basis "Ley General de Sociedades 19.550 (+ Ley 27.349 for SAS)"
          :national-spec "TAD (Trámites a Distancia) filing"
          :provenance "https://www.argentina.gob.ar/justicia/igj"
          :notes "Commercial registries are per-jurisdiction (IGJ covers the City of Buenos Aires; provinces keep their own Registro Público) -- IGJ is the exemplar authority here, same style as USA-DE."
          :required-docs ["Estatuto / instrumento constitutivo"
                          "Founder identification (DNI/CUIT)"
                          "Registered legal address (sede social)"
                          "Capital deposit evidence"
                          "CUIT tax registration"]}
   ;; ---- R2 expansion (2026-07-13): twelve more jurisdictions, same
   ;; discipline -- every entry cites the real national registry authority.
   "SAU" {:name "Saudi Arabia"
          :owner-authority "وزارة التجارة (Ministry of Commerce) / Saudi Business Center"
          :legal-basis "Companies Law (Royal Decree M/132, 2022)"
          :national-spec "Saudi Business Center unified registration"
          :provenance "https://mc.gov.sa/"
          :required-docs ["Articles of association"
                          "Founder/manager identification"
                          "Commercial registration (CR) application"
                          "Registered national address"
                          "Capital declaration"]}
   "ARE" {:name "United Arab Emirates"
          :owner-authority "Ministry of Economy (federal) / per-emirate Departments of Economic Development"
          :legal-basis "Federal Decree-Law No. 32/2021 on Commercial Companies"
          :national-spec "Per-emirate DED licensing (mainland) / free-zone registrars"
          :provenance "https://www.moec.gov.ae/"
          :notes "Incorporation is per-emirate (DED) or per-free-zone; the federal Ministry of Economy sets the company-law frame -- exemplar note, same style as USA-DE/ARG."
          :required-docs ["Memorandum of association"
                          "Trade name reservation"
                          "Founder/manager identification"
                          "Registered office / Ejari lease"
                          "Initial approval + licence issuance"]}
   "EGY" {:name "Egypt"
          :owner-authority "GAFI (General Authority for Investment and Free Zones)"
          :legal-basis "Companies Law No. 159/1981 / Investment Law No. 72/2017"
          :national-spec "GAFI investor services / electronic incorporation"
          :provenance "https://www.gafi.gov.eg/"
          :required-docs ["Articles of association"
                          "Founder identification"
                          "Bank certificate of capital deposit"
                          "Registered office address"
                          "Commercial registry entry + tax card"]}
   "PAK" {:name "Pakistan"
          :owner-authority "Securities and Exchange Commission of Pakistan (SECP)"
          :legal-basis "Companies Act 2017"
          :national-spec "SECP eZfile"
          :provenance "https://www.secp.gov.pk/"
          :required-docs ["Memorandum and articles of association"
                          "Company name reservation"
                          "Director/subscriber identification (CNIC/NICOP)"
                          "Registered office address"
                          "Declaration of compliance"]}
   "BGD" {:name "Bangladesh"
          :owner-authority "Registrar of Joint Stock Companies and Firms (RJSC)"
          :legal-basis "Companies Act 1994"
          :national-spec "RJSC online registration"
          :provenance "https://www.rjsc.gov.bd/"
          :required-docs ["Memorandum and articles of association"
                          "Name clearance certificate"
                          "Director/subscriber identification"
                          "Registered office address"
                          "Filing fees / stamp duty evidence"]}
   "UKR" {:name "Ukraine"
          :owner-authority "Ministry of Justice — Unified State Register (EDR) via state registrars"
          :legal-basis "Law of Ukraine on State Registration of Legal Entities, Individual Entrepreneurs and Public Formations"
          :national-spec "Diia portal / EDR online"
          :provenance "https://usr.minjust.gov.ua/"
          :required-docs ["Founding document (statute or model charter election)"
                          "Founders' decision/minutes"
                          "Founder identification"
                          "Registered legal address"
                          "State registration application"]}
   "KAZ" {:name "Kazakhstan"
          :owner-authority "Ministry of Justice — state registration via eGov/eOtinish"
          :legal-basis "Entrepreneurial Code / Law on State Registration of Legal Entities"
          :national-spec "eGov.kz electronic registration"
          :provenance "https://egov.kz/"
          :required-docs ["Charter (or model charter election)"
                          "Foundation decision/minutes"
                          "Founder identification (IIN/BIN)"
                          "Registered legal address"
                          "State registration application"]}
   "PER" {:name "Peru"
          :owner-authority "SUNARP (Superintendencia Nacional de los Registros Públicos)"
          :legal-basis "Ley General de Sociedades No. 26887"
          :national-spec "SID-SUNARP electronic filing (via notary)"
          :provenance "https://www.sunarp.gob.pe/"
          :required-docs ["Escritura pública (notarised deed of incorporation)"
                          "Founder identification (DNI/RUC)"
                          "Registered address (domicilio)"
                          "Capital subscription/payment evidence"
                          "RUC tax registration"]}
   "COL" {:name "Colombia"
          :owner-authority "Cámaras de Comercio (chamber commercial registries) / RUES"
          :legal-basis "Código de Comercio / Ley 1258 de 2008 (SAS)"
          :national-spec "RUES (Registro Único Empresarial y Social)"
          :provenance "https://www.rues.org.co/"
          :required-docs ["Constitution document (private document for SAS or escritura pública)"
                          "Founder identification"
                          "Registered address"
                          "RUT tax registration (DIAN)"
                          "Chamber of commerce registration fee"]}
   "GRC" {:name "Greece"
          :owner-authority "Γ.Ε.ΜΗ. (GEMI, General Commercial Registry) via One-Stop Shops"
          :legal-basis "Law 4919/2022 (GEMI) / Law 4548/2018 (sociétés anonymes)"
          :national-spec "e-GEMI / electronic One-Stop Shop (e-YMS)"
          :provenance "https://www.businessregistry.gr/"
          :required-docs ["Articles of association (or model statute)"
                          "Founder identification / tax number (AFM)"
                          "Registered office address"
                          "GEMI registration application"
                          "Capital declaration"]}
   "AUT" {:name "Austria"
          :owner-authority "Firmenbuch (commercial register at the regional courts)"
          :legal-basis "UGB (Unternehmensgesetzbuch) / GmbHG"
          :national-spec "JustizOnline / notarial filing to the Firmenbuch"
          :provenance "https://www.justiz.gv.at/"
          :required-docs ["Notarised articles of association (Gesellschaftsvertrag)"
                          "Managing director appointment + specimen signature"
                          "Founder identification"
                          "Registered office address"
                          "Capital deposit bank confirmation"]}
   "ROU" {:name "Romania"
          :owner-authority "ONRC (Oficiul Național al Registrului Comerțului)"
          :legal-basis "Legea nr. 31/1990 privind societățile"
          :national-spec "ONRC online portal"
          :provenance "https://www.onrc.ro/"
          :required-docs ["Constitutive act (act constitutiv)"
                          "Company name reservation"
                          "Founder/administrator identification"
                          "Registered office (sediu social) proof"
                          "Capital deposit evidence"]}
   "CHL" {:name "Chile"
          :owner-authority "Registro de Empresas y Sociedades (Ministerio de Economía) / Conservador de Comercio (traditional route)"
          :legal-basis "Ley 20.659 (simplified regime) / Código de Comercio"
          :national-spec "\"Tu Empresa en un Día\" electronic registry"
          :provenance "https://www.registrodeempresasysociedades.cl/"
          :required-docs ["Electronic statute (estatuto)"
                          "Founder identification (RUN/RUT)"
                          "Registered address in Chile"
                          "Capital declaration"
                          "SII tax initiation (inicio de actividades)"]}
   ;; ---- R3 expansion (2026-07-13): ten African jurisdictions, same
   ;; discipline. CIV/SEN sit in the OHADA uniform-company-law zone
   ;; (Acte uniforme AUSCGIE) -- the uniform law is supranational but the
   ;; RCCM register and one-stop shop are national; entries cite both.
   "KEN" {:name "Kenya"
          :owner-authority "Business Registration Service (BRS) via eCitizen"
          :legal-basis "Companies Act, 2015"
          :national-spec "eCitizen business registration"
          :provenance "https://brs.go.ke/"
          :required-docs ["Memorandum and articles of association (or model articles)"
                          "Company name reservation"
                          "Director/shareholder identification"
                          "Registered office address"
                          "Statement of nominal capital"]}
   "GHA" {:name "Ghana"
          :owner-authority "Office of the Registrar of Companies (ORC)"
          :legal-basis "Companies Act, 2019 (Act 992)"
          :national-spec "ORC online business registration"
          :provenance "https://orc.gov.gh/"
          :required-docs ["Company constitution (or standard constitution election)"
                          "Director/subscriber identification (Ghana Card/TIN)"
                          "Registered office address"
                          "Stated capital declaration"
                          "Auditor consent (where required)"]}
   "ETH" {:name "Ethiopia"
          :owner-authority "Ministry of Trade and Regional Integration — commercial registration"
          :legal-basis "Commercial Code of Ethiopia (2021 revision)"
          :national-spec "eTrade online registration and licensing"
          :provenance "https://etrade.gov.et/"
          :required-docs ["Memorandum and articles of association"
                          "Founder/manager identification"
                          "Registered office address"
                          "Capital declaration"
                          "Commercial registration certificate application"]}
   "TZA" {:name "Tanzania"
          :owner-authority "BRELA (Business Registrations and Licensing Agency)"
          :legal-basis "Companies Act (Cap. 212)"
          :national-spec "BRELA Online Registration System (ORS)"
          :provenance "https://www.brela.go.tz/"
          :required-docs ["Memorandum and articles of association"
                          "Company name clearance"
                          "Director/shareholder identification"
                          "Registered office address"
                          "Declaration of compliance"]}
   "UGA" {:name "Uganda"
          :owner-authority "Uganda Registration Services Bureau (URSB)"
          :legal-basis "Companies Act, 2012"
          :national-spec "URSB online business registration"
          :provenance "https://ursb.go.ug/"
          :required-docs ["Memorandum and articles of association"
                          "Company name reservation"
                          "Director/subscriber identification"
                          "Registered office address"
                          "Statement of nominal capital"]}
   "RWA" {:name "Rwanda"
          :owner-authority "Rwanda Development Board (RDB) — Office of the Registrar General"
          :legal-basis "Law No. 007/2021 Governing Companies"
          :national-spec "RDB online business registration"
          :provenance "https://rdb.rw/"
          :required-docs ["Articles of association (or standard form)"
                          "Founder/director identification"
                          "Registered office address in Rwanda"
                          "Share capital information"
                          "Registration application (online)"]}
   "MAR" {:name "Morocco"
          :owner-authority "OMPIC / tribunal commercial registries (Registre de Commerce)"
          :legal-basis "Loi 17-95 (SA) / Loi 5-96 (SARL)"
          :national-spec "OMPIC DirectInfo / CRI one-stop shops"
          :provenance "https://www.ompic.ma/"
          :required-docs ["Statuts (articles of association)"
                          "Certificat négatif (name clearance)"
                          "Founder/manager identification"
                          "Registered office (domiciliation) proof"
                          "Capital deposit evidence (where required)"]}
   "DZA" {:name "Algeria"
          :owner-authority "CNRC (Centre National du Registre de Commerce)"
          :legal-basis "Code de commerce algérien"
          :national-spec "CNRC / SIDJILCOM electronic register"
          :provenance "https://cnrc.dz/"
          :required-docs ["Statuts notariés"
                          "Founder/manager identification"
                          "Registered office lease or ownership proof"
                          "Capital deposit evidence"
                          "Commercial register application"]}
   "CIV" {:name "Côte d'Ivoire"
          :owner-authority "CEPICI guichet unique / RCCM (tribunal registry)"
          :legal-basis "OHADA Acte uniforme relatif au droit des sociétés commerciales et du GIE (AUSCGIE)"
          :national-spec "CEPICI one-stop shop electronic filing"
          :provenance "https://www.cepici.gouv.ci/"
          :notes "OHADA member: company law is the supranational AUSCGIE uniform act; the RCCM register and the CEPICI one-stop shop are national."
          :required-docs ["Statuts (notarised or SSGC private deed as applicable)"
                          "Founder/manager identification"
                          "Registered office proof"
                          "Capital deposit evidence"
                          "RCCM registration application"]}
   "SEN" {:name "Senegal"
          :owner-authority "APIX guichet unique (Bureau d'appui à la création d'entreprise) / RCCM"
          :legal-basis "OHADA Acte uniforme relatif au droit des sociétés commerciales et du GIE (AUSCGIE)"
          :national-spec "APIX one-stop shop"
          :provenance "https://www.apix.sn/"
          :notes "OHADA member: same AUSCGIE uniform act as CIV; RCCM registration is handled nationally through the APIX one-stop shop."
          :required-docs ["Statuts"
                          "Founder/manager identification (CNI/NINEA)"
                          "Registered office proof"
                          "Capital deposit evidence"
                          "RCCM registration application"]}
   ;; ---- R4 expansion (2026-07-13): twelve more jurisdictions
   ;; (central Europe, Gulf, south Asia), same discipline.
   "HUN" {:name "Hungary"
          :owner-authority "Törvényszéki cégbíróságok (court company registries) / Company Information Service"
          :legal-basis "2006. évi V. törvény (Company Registration Act) / Ptk. (Civil Code)"
          :national-spec "e-cégeljárás (electronic company procedure)"
          :provenance "https://www.e-cegjegyzek.hu/"
          :required-docs ["Deed of foundation (attorney-countersigned)"
                          "Founder/executive identification"
                          "Registered seat proof"
                          "Capital declaration"
                          "Court registration application"]}
   "SVK" {:name "Slovakia"
          :owner-authority "Obchodný register (Ministry of Justice / registry courts)"
          :legal-basis "Obchodný zákonník (Act No. 513/1991)"
          :national-spec "Obchodný register online filing"
          :provenance "https://www.orsr.sk/"
          :required-docs ["Foundation deed / memorandum"
                          "Founder/executive identification"
                          "Registered office consent"
                          "Capital deposit declaration"
                          "Trade licence (živnosť) where applicable"]}
   "SVN" {:name "Slovenia"
          :owner-authority "AJPES (Agency for Public Legal Records) — Slovenian Business Register"
          :legal-basis "ZGD-1 (Companies Act)"
          :national-spec "eVEM / SPOT one-stop registration"
          :provenance "https://www.ajpes.si/"
          :required-docs ["Articles of association"
                          "Founder identification"
                          "Registered office proof"
                          "Capital deposit evidence"
                          "SPOT registration application"]}
   "HRV" {:name "Croatia"
          :owner-authority "Sudski registar (court register, Ministry of Justice)"
          :legal-basis "Zakon o trgovačkim društvima (Companies Act)"
          :national-spec "START online incorporation / sudski registar"
          :provenance "https://sudreg.pravosudje.hr/"
          :required-docs ["Notarised founding act"
                          "Founder/board identification"
                          "Registered seat proof"
                          "Capital deposit evidence"
                          "Court register application"]}
   "BGR" {:name "Bulgaria"
          :owner-authority "Registry Agency — Търговски регистър (Commercial Register)"
          :legal-basis "Търговски закон (Commerce Act)"
          :national-spec "Registry Agency electronic portal"
          :provenance "https://portal.registryagency.bg/"
          :required-docs ["Articles of association / founding minutes"
                          "Manager specimen signature (notarised)"
                          "Founder identification"
                          "Registered seat and management address"
                          "Capital deposit bank certificate"]}
   "LTU" {:name "Lithuania"
          :owner-authority "Registrų centras (State Enterprise Centre of Registers)"
          :legal-basis "Civil Code / Law on Companies"
          :national-spec "Registrų centras self-service portal"
          :provenance "https://www.registrucentras.lt/"
          :required-docs ["Articles of association (or model form)"
                          "Founder identification"
                          "Registered office consent"
                          "Capital accumulation account evidence"
                          "Registration application"]}
   "LVA" {:name "Latvia"
          :owner-authority "Uzņēmumu reģistrs (Register of Enterprises)"
          :legal-basis "Komerclikums (Commercial Law)"
          :national-spec "Latvija.gov.lv e-services"
          :provenance "https://www.ur.gov.lv/"
          :required-docs ["Memorandum/articles of association"
                          "Founder/board identification"
                          "Legal address proof"
                          "Capital payment confirmation"
                          "Registration application"]}
   "LUX" {:name "Luxembourg"
          :owner-authority "LBR (Luxembourg Business Registers) — RCS"
          :legal-basis "Loi du 10 août 1915 concernant les sociétés commerciales"
          :national-spec "LBR electronic filing (RCS)"
          :provenance "https://www.lbr.lu/"
          :required-docs ["Notarial deed of incorporation (SA/SARL)"
                          "Founder/manager identification"
                          "Registered office proof"
                          "Capital blocking certificate"
                          "RCS registration"]}
   "QAT" {:name "Qatar"
          :owner-authority "Ministry of Commerce and Industry (MOCI)"
          :legal-basis "Commercial Companies Law No. 11 of 2015"
          :national-spec "MOCI single-window (Invest Easy)"
          :provenance "https://www.moci.gov.qa/"
          :required-docs ["Articles of association (authenticated)"
                          "Founder/manager identification"
                          "Commercial registration application"
                          "Registered premises evidence"
                          "Trade name reservation"]}
   "KWT" {:name "Kuwait"
          :owner-authority "Ministry of Commerce and Industry"
          :legal-basis "Companies Law No. 1 of 2016"
          :national-spec "Kuwait Business Center one-stop"
          :provenance "https://www.moci.gov.kw/"
          :required-docs ["Memorandum of association (authenticated)"
                          "Founder identification"
                          "Registered premises evidence"
                          "Capital deposit certificate"
                          "Commercial registration application"]}
   "LKA" {:name "Sri Lanka"
          :owner-authority "Department of the Registrar of Companies"
          :legal-basis "Companies Act No. 7 of 2007"
          :national-spec "eROC online registration"
          :provenance "https://www.drc.gov.lk/"
          :required-docs ["Articles of association (or model articles)"
                          "Form 1 (registration) + consents (Forms 18/19)"
                          "Director/secretary identification"
                          "Registered office address"
                          "Name reservation"]}
   "JOR" {:name "Jordan"
          :owner-authority "Companies Control Department (Ministry of Industry, Trade and Supply)"
          :legal-basis "Companies Law No. 22 of 1997 (as amended)"
          :national-spec "CCD electronic registration"
          :provenance "https://ccd.gov.jo/"
          :required-docs ["Memorandum and articles of association"
                          "Founder identification"
                          "Registered office proof"
                          "Capital declaration"
                          "Registration application"]}
   ;; ---- R5 expansion (2026-07-13): twelve more jurisdictions
   ;; (Latin America, Caucasus/CIS), same discipline.
   "ECU" {:name "Ecuador"
          :owner-authority "Superintendencia de Compañías, Valores y Seguros (SUPERCIAS)"
          :legal-basis "Ley de Compañías"
          :national-spec "SUPERCIAS electronic incorporation portal"
          :provenance "https://www.supercias.gob.ec/"
          :required-docs ["Escritura de constitución / electronic statute"
                          "Founder identification (cédula/RUC)"
                          "Registered domicile"
                          "Capital subscription evidence"
                          "RUC tax registration"]}
   "URY" {:name "Uruguay"
          :owner-authority "DGR — Registro de Personas Jurídicas (Registro Nacional de Comercio)"
          :legal-basis "Ley 16.060 de Sociedades Comerciales"
          :national-spec "\"Empresa en el Día\" one-stop portal"
          :provenance "https://www.gub.uy/"
          :required-docs ["Estatuto / contrato social"
                          "Founder identification"
                          "Registered address"
                          "Capital declaration"
                          "RUT (DGI) tax registration"]}
   "PRY" {:name "Paraguay"
          :owner-authority "SUACE one-stop / Registro de Personas Jurídicas (Abogacía del Tesoro)"
          :legal-basis "Código Civil / Ley 6480/2020 (EAS simplified companies)"
          :national-spec "SUACE (Sistema Unificado de Apertura y Cierre de Empresas)"
          :provenance "https://www.suace.gov.py/"
          :required-docs ["Estatuto / instrumento constitutivo"
                          "Founder identification"
                          "Registered address"
                          "Capital declaration"
                          "RUC tax registration"]}
   "BOL" {:name "Bolivia"
          :owner-authority "SEPREC (Servicio Plurinacional de Registro de Comercio)"
          :legal-basis "Código de Comercio"
          :national-spec "SEPREC digital registry (successor to Fundempresa)"
          :provenance "https://www.seprec.gob.bo/"
          :required-docs ["Escritura de constitución / testimonio"
                          "Founder identification"
                          "Registered address"
                          "Capital declaration"
                          "NIT tax registration"]}
   "CRI" {:name "Costa Rica"
          :owner-authority "Registro Nacional — Registro de Personas Jurídicas"
          :legal-basis "Código de Comercio"
          :national-spec "RNP Digital / CrearEmpresa"
          :provenance "https://www.rnpdigital.com/"
          :required-docs ["Escritura de constitución (notarised)"
                          "Founder identification"
                          "Registered address"
                          "Capital subscription evidence"
                          "Legal books registration"]}
   "PAN" {:name "Panama"
          :owner-authority "Registro Público de Panamá"
          :legal-basis "Ley 32 de 1927 (sociedades anónimas)"
          :national-spec "Registro Público electronic filing (via resident agent)"
          :provenance "https://www.registro-publico.gob.pa/"
          :notes "Incorporation requires a resident agent (Panamanian lawyer/firm) -- structural feature of the 1927 regime, noted honestly rather than hidden."
          :required-docs ["Pacto social (articles, notarised)"
                          "Resident agent appointment"
                          "Subscriber identification"
                          "Registered office (agent address)"
                          "Registro Público filing"]}
   "DOM" {:name "Dominican Republic"
          :owner-authority "Cámaras de Comercio — Registro Mercantil"
          :legal-basis "Ley 479-08 General de Sociedades Comerciales"
          :national-spec "Formalízate one-stop portal"
          :provenance "https://formalizate.gob.do/"
          :required-docs ["Estatutos sociales"
                          "Founder identification"
                          "Company name registration (ONAPI)"
                          "Registered address"
                          "RNC tax registration"]}
   "GTM" {:name "Guatemala"
          :owner-authority "Registro Mercantil General de la República"
          :legal-basis "Código de Comercio (Decreto 2-70)"
          :national-spec "Registro Mercantil e-portal / minegocio.gt"
          :provenance "https://www.registromercantil.gob.gt/"
          :required-docs ["Escritura pública de constitución"
                          "Founder identification"
                          "Registered address"
                          "Capital deposit evidence"
                          "NIT tax registration"]}
   "GEO" {:name "Georgia"
          :owner-authority "NAPR (National Agency of Public Registry, Ministry of Justice)"
          :legal-basis "Law of Georgia on Entrepreneurs (2021)"
          :national-spec "NAPR same-day registration / Public Service Halls"
          :provenance "https://napr.gov.ge/"
          :required-docs ["Charter (or standard charter election)"
                          "Founders' resolution"
                          "Founder/director identification"
                          "Registered legal address"
                          "Registration application"]}
   "ARM" {:name "Armenia"
          :owner-authority "State Register of Legal Entities (Ministry of Justice)"
          :legal-basis "Law on State Registration of Legal Entities"
          :national-spec "e-register.am online registration"
          :provenance "https://www.e-register.am/"
          :required-docs ["Charter"
                          "Founders' decision"
                          "Founder/director identification"
                          "Registered address"
                          "Registration application"]}
   "AZE" {:name "Azerbaijan"
          :owner-authority "State Tax Service — one-window business registration"
          :legal-basis "Civil Code / Law on State Registration of Legal Entities"
          :national-spec "e-taxes portal electronic registration"
          :provenance "https://www.taxes.gov.az/"
          :required-docs ["Charter"
                          "Founders' resolution"
                          "Founder/legal-representative identification"
                          "Registered legal address"
                          "TIN registration"]}
   "MDA" {:name "Moldova"
          :owner-authority "Agenția Servicii Publice (ASP)"
          :legal-basis "Law on State Registration of Legal Entities and Individual Entrepreneurs"
          :national-spec "ASP registration service (24h standard)"
          :provenance "https://asp.gov.md/"
          :required-docs ["Constitutive act"
                          "Founders' decision"
                          "Founder/administrator identification"
                          "Registered office proof"
                          "Registration application"]}
   ;; ---- R6 expansion (2026-07-13): ten more jurisdictions (small
   ;; Europe, Balkans, Asia). BIH/MNE/FJI deliberately deferred: their
   ;; registry portal provenance could not be pinned with confidence,
   ;; and a wobbly URL is worse than an honest gap.
   "ISL" {:name "Iceland"
          :owner-authority "Fyrirtækjaskrá (Company Register, Iceland Revenue and Customs — Skatturinn)"
          :legal-basis "Act No. 138/1994 (private limited companies) / Act No. 2/1995 (public limited companies)"
          :national-spec "Skatturinn electronic company registration"
          :provenance "https://www.skatturinn.is/"
          :required-docs ["Articles of association"
                          "Founder/board identification (kennitala)"
                          "Registered office address"
                          "Share capital confirmation"
                          "Registration application"]}
   "MLT" {:name "Malta"
          :owner-authority "Malta Business Registry (MBR)"
          :legal-basis "Companies Act (Cap. 386)"
          :national-spec "MBR online registry (BAROS)"
          :provenance "https://mbr.mt/"
          :required-docs ["Memorandum and articles of association"
                          "Founder/director identification"
                          "Registered office in Malta"
                          "Share capital deposit evidence"
                          "Registration fee"]}
   "CYP" {:name "Cyprus"
          :owner-authority "Department of Registrar of Companies and Intellectual Property (DRCIP)"
          :legal-basis "Companies Law (Cap. 113)"
          :national-spec "DRCIP e-filing"
          :provenance "https://www.companies.gov.cy/"
          :required-docs ["Memorandum and articles of association (via lawyer's declaration HE1)"
                          "Director/secretary/shareholder identification"
                          "Registered office address"
                          "Name approval"
                          "Registration forms (HE1/HE2/HE3)"]}
   "SRB" {:name "Serbia"
          :owner-authority "APR (Agencija za privredne registre — Serbian Business Registers Agency)"
          :legal-basis "Zakon o privrednim društvima (Law on Companies)"
          :national-spec "APR e-registration"
          :provenance "https://www.apr.gov.rs/"
          :required-docs ["Founding act (memorandum/decision)"
                          "Founder identification"
                          "Registered seat"
                          "Capital payment/subscription evidence"
                          "Registration application"]}
   "ALB" {:name "Albania"
          :owner-authority "QKB (Qendra Kombëtare e Biznesit — National Business Center)"
          :legal-basis "Law No. 9901/2008 on Entrepreneurs and Companies"
          :national-spec "e-Albania / QKB one-stop registration"
          :provenance "https://qkb.gov.al/"
          :required-docs ["Statute/founding act (or standard form)"
                          "Founder identification"
                          "Registered office address"
                          "Capital declaration"
                          "Registration application"]}
   "MKD" {:name "North Macedonia"
          :owner-authority "Central Registry of the Republic of North Macedonia (Централен регистар)"
          :legal-basis "Law on Trade Companies"
          :national-spec "Central Registry one-stop-shop system"
          :provenance "https://www.crm.com.mk/"
          :required-docs ["Founding agreement/statement"
                          "Founder/manager identification"
                          "Registered seat"
                          "Capital declaration"
                          "Registration application"]}
   "KHM" {:name "Cambodia"
          :owner-authority "Ministry of Commerce — Business Registration Department"
          :legal-basis "Law on Commercial Enterprises (2005)"
          :national-spec "Online Business Registration (CamDX single portal)"
          :provenance "https://www.registrationservices.gov.kh/"
          :required-docs ["Articles of incorporation"
                          "Director/shareholder identification"
                          "Registered office address"
                          "Capital declaration"
                          "Online registration via CamDX"]}
   "NPL" {:name "Nepal"
          :owner-authority "Office of the Company Registrar (OCR)"
          :legal-basis "Companies Act, 2063 (2006)"
          :national-spec "OCR online company registration"
          :provenance "https://ocr.gov.np/"
          :required-docs ["Memorandum and articles of association"
                          "Promoter identification (citizenship/passport)"
                          "Registered office address"
                          "Capital structure declaration"
                          "Registration application"]}
   "MNG" {:name "Mongolia"
          :owner-authority "General Authority for State Registration (Улсын бүртгэлийн ерөнхий газар)"
          :legal-basis "Company Law of Mongolia (2011)"
          :national-spec "State registration e-services (burtgel.gov.mn)"
          :provenance "https://burtgel.gov.mn/"
          :required-docs ["Company charter"
                          "Founders' resolution"
                          "Founder identification"
                          "Registered legal address"
                          "State registration application"]}
   "BRN" {:name "Brunei Darussalam"
          :owner-authority "Registry of Companies and Business Names (Ministry of Finance and Economy)"
          :legal-basis "Companies Act (Cap. 39)"
          :national-spec "OCP (One Common Portal) registration"
          :provenance "https://www.mofe.gov.bn/"
          :required-docs ["Memorandum and articles of association"
                          "Director/shareholder identification"
                          "Registered office in Brunei"
                          "Name reservation"
                          "Registration via OCP"]}
   "RUS" {:name "Russia"
          :owner-authority "Federal Tax Service (ФНС России) -- Unified State Register of Legal Entities"
          :legal-basis "Federal Law No. 129-FZ 'On State Registration of Legal Entities and Individual Entrepreneurs'"
          :national-spec "EGRUL (Единый государственный реестр юридических лиц)"
          :provenance "https://egrul.nalog.ru/"
          :required-docs ["Charter (устав)"
                          "Founder decision/minutes on incorporation"
                          "Registered legal address confirmation"
                          "State duty payment receipt"
                          "Application form P11001"]}
   "TWN" {:name "Taiwan"
          :owner-authority "Department of Commerce, Ministry of Economic Affairs"
          :legal-basis "Company Act (公司法)"
          :national-spec "GCIS Company & Business Registration System"
          :provenance "https://gcis.nat.gov.tw/"
          :required-docs ["Articles of incorporation (公司章程)"
                          "Director/shareholder identification"
                          "Registered capital verification"
                          "Company name pre-check"
                          "Registration application"]}
   "VGB" {:name "British Virgin Islands"
          :owner-authority "Registry of Corporate Affairs (BVI Financial Services Commission)"
          :legal-basis "BVI Business Companies Act, 2004"
          :national-spec "VIRRGIN online registry system"
          :provenance "https://www.bvifsc.vg/"
          :required-docs ["Memorandum and articles of association"
                          "Registered agent with a BVI address"
                          "Director/beneficial owner identification"
                          "Name reservation"
                          "Incorporation fee"]}
   "CYM" {:name "Cayman Islands"
          :owner-authority "General Registry (Registrar of Companies)"
          :legal-basis "Companies Act (2023 Revision)"
          :national-spec "General Registry online filing"
          :provenance "https://www.ciregistry.ky/"
          :required-docs ["Memorandum and articles of association"
                          "Registered office in the Cayman Islands"
                          "Director/beneficial owner identification"
                          "Name reservation"
                          "Registration fee"]}
   "BMU" {:name "Bermuda"
          :owner-authority "Registrar of Companies (Bermuda Ministry of Finance)"
          :legal-basis "Companies Act 1981"
          :national-spec "Registrar of Companies e-filing"
          :provenance "https://www.gov.bm/registrar-of-companies"
          :required-docs ["Memorandum of association"
                          "Registered office in Bermuda"
                          "Director identification"
                          "Beneficial ownership declaration"
                          "Incorporation fee"]}
   "LIE" {:name "Liechtenstein"
          :owner-authority "Office of Land and Public Registration (Amt für Justiz -- Handelsregister)"
          :legal-basis "Personen- und Gesellschaftsrecht (PGR)"
          :national-spec "Handelsregister online extract system"
          :provenance "https://www.llv.li/"
          :required-docs ["Articles of association (Statuten)"
                          "Director/board identification"
                          "Registered office in Liechtenstein"
                          "Capital deposit confirmation"
                          "Registration application"]}})

(defn spec-basis
  "The jurisdiction's requirement map, or nil -- nil means NO spec-basis,
  and the governor must hold any proposal that tries to file for it."
  [iso3]
  (get catalog iso3))

(defn coverage
  "Honest coverage report: how many of the requested jurisdictions actually
  have a spec-basis entry. Never report a missing jurisdiction as covered."
  ([] (coverage (keys catalog)))
  ([iso3s]
   (let [have (filter catalog iso3s)
         missing (remove catalog iso3s)]
     {:requested (count iso3s)
      :covered (count have)
      :covered-jurisdictions (vec (sort have))
      :missing-jurisdictions (vec (sort missing))
      :note (str "cloud-itonami-isic-6910 R0: " (count catalog)
                 " jurisdictions seeded with an official spec-basis. "
                 "This is a starting catalog, not a survey of all ~194 "
                 "jurisdictions -- extend `formation.facts/catalog`, never "
                 "fabricate a jurisdiction's requirements.")})))

(defn required-docs-satisfied?
  "Does `submitted` (a set/coll of doc keywords or strings) satisfy every
  required doc listed for `iso3`? Missing spec-basis -> never satisfied."
  [iso3 submitted]
  (when-let [{:keys [required-docs]} (spec-basis iso3)]
    (let [need (count required-docs)
          have (count (filter (set submitted) required-docs))]
      (= need have))))

(defn doc-checklist [iso3]
  (:required-docs (spec-basis iso3) []))
